// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace lab6._0.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("API.Entities.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsDone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            Created = 1,
                            Description = "a",
                            IsDone = 0
                        },
                        new
                        {
                            Id = 8,
                            Created = 1,
                            Description = "b",
                            IsDone = 0
                        },
                        new
                        {
                            Id = 9,
                            Created = 1,
                            Description = "c",
                            IsDone = 1
                        },
                        new
                        {
                            Id = 10,
                            Created = 1,
                            Description = "d",
                            IsDone = 0
                        },
                        new
                        {
                            Id = 11,
                            Created = 0,
                            Description = "e",
                            IsDone = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
